### ISSUE TITLE
The address was already in use

### ISSUE THREAD

**Issue by classicrob** [lambdaisland/witchcraft#3]
Hi! I tried getting this setup so I could show my kid cousins and maybe get them interested in code, but I ended up with this error stack trace. Would you please advise?

I loaded this code into my REPL:

```clojure
(ns witchcraft-practice.core
  (:require [lambdaisland.witchcraft :as wc]))

(wc/start!)
```

And ended up with this:

```clojure
18:27:06 [INFO] This server is running Glowstone version 2021.7.0-SNAPSHOT.4ad0ccb (MC: 1.12.2) (Implementing API version 1.12.2-R6.0-SNAPSHOT)
18:27:08 [INFO] Recipes: 307 shaped, 63 shapeless, 26 furnace, 10 dynamic, 44 fuels.
> 
18:27:10 [INFO] Scanning plugins...
> 
18:27:10 [INFO] Preparing spawn for world...
> Connecting to local nREPL server...
nREPL server started on port 60301 on host 127.0.0.1 - nrepl://127.0.0.1:60301
Clojure 1.10.1

18:27:13 [INFO] Preparing spawn for world: 0%
> 
18:27:14 [INFO] Preparing spawn for world: 1%
> 
18:27:15 [INFO] Preparing spawn for world: 4%
> 
18:27:16 [INFO] Preparing spawn for world: 14%
> 
18:27:17 [INFO] Preparing spawn for world: 28%
> 
18:27:18 [INFO] Preparing spawn for world: 43%
> 
18:27:19 [INFO] Preparing spawn for world: 57%
> 
18:27:20 [INFO] Preparing spawn for world: 73%
> 
18:27:21 [INFO] Preparing spawn for world: 87%
> 
18:27:22 [INFO] Preparing spawn for world: done
> 
18:27:22 [INFO] Preparing spawn for world_nether...
> 
18:27:23 [INFO] Preparing spawn for world_nether: 40%
> 
18:27:24 [INFO] Preparing spawn for world_nether: 89%
> 
18:27:24 [INFO] Preparing spawn for world_nether: done
> 
18:27:24 [INFO] Preparing spawn for world_the_end...
> 
18:27:25 [INFO] Preparing spawn for world_the_end: done
> 
18:27:25 [WARNING] Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
> 
18:27:25 [INFO] Binding server to 0.0.0.0:25565...
> 
18:27:25 [SEVERE] Failed to bind server to 0.0.0.0:25565.
> 
18:27:25 [SEVERE] The address was already in use.
Check that no server is already running on that port.
If needed, try killing all Java processes using Task Manager or similar.
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:550)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:249)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
> 
> 
Process finished with exit code 1
```

My project.clj file has this:

```clojure
(defproject witchcraft-practice "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [com.lambdaisland/witchcraft "0.0.28"]]
  :repl-options {:init-ns witchcraft-practice.core}
  :repositories {"glowstone-repo" "https://repo.glowstone.net/content/repositories/snapshots/"
                 "aikar" "https://repo.aikar.co/nexus/content/repositories/aikar-release/"})
```

**Comment by plexus** [comment]
Hi @classicrob , that looks good all in all. Is there any chance you started the process twice? You can see with `jcmd` if there are other JVM processes active. 25565 is also the port generally often used by Minecraft servers, so if you have another server software running that could also be interfering.

**Comment by classicrob** [comment]
I ran `jcmd` and this was the output.

I don't think I have another server software running... this is the first time I've ever opened Minecraft


46324 /Users/roberthaisfield/Downloads/glowstone.jar
71094 jdk.jcmd/sun.tools.jcmd.JCmd

**Comment by classicrob** [comment]
If anyone else experiences this issue, I just solved it by running this shell command and then trying again:

pkill -f 'java -jar'

**Comment by plexus** [comment]
>  46324 /Users/roberthaisfield/Downloads/glowstone.jar

Seems you also had Glowstone running by itself. When using Witchcraft this isn't necessary, we start Glowstone from inside the Clojure REPL.

Maybe we should point that out explicitly in the README?

**Comment by classicrob** [comment]
That would be helpful! When I was going through the Readme, I interpreted it as I should download and run Glowstone before I started with Witchcraft
